In [ ]:
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import folium

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# 데이터 로드

### 운영 이력과 자전거 스테이션 데이터 로드

In [ ]:
df_OH = pd.read_csv('01.운영 이력(Bike_Time(s).csv') ## 이용시간을 구한 운영이력 dataframe가져오기
df_bike_rent = pd.read_csv('02.자전거스테이션.csv')
df_bike_return = pd.read_csv('02.자전거스테이션.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [ ]:
 # LEAS_STAT,LEAS_NO데이터 지워주어 필요한 데이터만 가져오기
del df_OH['LEAS_STAT']

In [ ]:
df_OH.columns = ['대여 번호', '대여 시간', '대여 스테이션 번호', '대여 거치대 번호', '반납 시간','반납 스테이션 번호','반납 거치대 번호','추정 이동 거리', '회원 구분', '회원 번호', '비회원 번호', '자전거 번호', '관제 반납','이용 시간(s)']
# 컬럼 목록을 한글로 정리

In [ ]:
df_bike_rent.columns = ['대여 스테이션 번호','대여 STATION_NAME','대여 거치대 수량','대여 위도','대여 경도']
df_bike_return.columns = ['반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','반납 위도','반납 경도']

In [ ]:
df_merge = pd.merge(df_OH,df_bike_rent,on='대여 스테이션 번호',how='left')
df_merge_all = pd.merge(df_merge,df_bike_return,on='반납 스테이션 번호',how='left')

In [ ]:
df_OH_5 = df_merge_all[['대여 시간','대여 스테이션 번호','대여 STATION_NAME','대여 거치대 수량','반납 시간','반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','추정 이동 거리','회원 번호','비회원 번호','관제 반납','이용 시간(s)','대여 위도','대여 경도','반납 위도','반납 경도']]
df_OH_6 = df_merge_all[['대여 시간','대여 스테이션 번호','대여 STATION_NAME','대여 거치대 수량','반납 시간','반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','추정 이동 거리','회원 번호','비회원 번호','관제 반납','이용 시간(s)','대여 위도','대여 경도','반납 위도','반납 경도']]

In [ ]:
## 대여 시간을 일별로 정리 해준다. 모든 데이터 이용 횟수는 대여시간 기준으로 정한다.
df_OH_5['대여 시간']=df_OH_5['대여 시간'].apply(lambda x : x[:10])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
## 스테이션 번호 int->str로 변경
df_OH_5['대여 스테이션 번호']=df_OH_5[['대여 스테이션 번호']].astype('str')
df_OH_5['반납 스테이션 번호']=df_OH_5[['반납 스테이션 번호']].astype('str')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
df_OH_6['대여 시간']=df_OH_6['대여 시간'].apply(lambda x : x[:4])  ## 대여 시간을 년도별로 정리 해준다. 모든 데이터 이용 횟수는 대여시간 기준으로 정한다.
## 스테이션 번호 int->str로 변경
df_OH_6['대여 스테이션 번호']=df_OH_6[['대여 스테이션 번호']].astype('str')
df_OH_6['반납 스테이션 번호']=df_OH_6[['반납 스테이션 번호']].astype('str')
df_OH_6

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

        대여 시간 대여 스테이션 번호   대여 STATION_NAME  ...       대여 경도      반납 위도       반납 경도
0        2017        213          마두1동 사거리  ...  126.787998  37.662030  126.768952
1        2017        231         국립암센터 맞은편  ...  126.784667  37.664181  126.784667
2        2017        119        ★화정역 4번 출구  ...  126.832925        NaN         NaN
3        2017        121            세일빌딩 앞  ...  126.830449  37.619519  126.820909
4        2017        320  ★산들마을 사거리 604동 앞  ...  126.777589  37.656722  126.771620
...       ...        ...               ...  ...         ...        ...         ...
3142683  2019        222             백석고 옆  ...  126.788060  37.648388  126.787636
3142684  2019        343            문화초교 옆  ...  126.768351  37.670203  126.768394
3142685  2019        333     SBS일산제작센터 맞은편  ...  126.765030  37.684534  126.761979
3142686  2019        264          ◆킨텍스 사거리  ...  126.748019  37.663673  126.767099
3142687  2019        214       ★마두역 교보생명 옆  ...  126.777358  37.652488  126.788060

[3142688 rows x 17 columns]

### 대여 스테이션 이용 횟수를 기준으로 

- 대여시간 별로 각각의 반납 스테이션 이용 횟수
- pivot data
- max
- min
- median
- 4분위(25)
- 4분위(75)
- mean
- 스테이션 총 이용 횟수
- pivot dataframe에 붙이기

In [ ]:
# group by를 통해 대여시간 별로 각각의 반납 스테이션 이용 횟수
station_day_return_count = (df_OH_5.groupby([df_OH_5['대여 시간'],df_OH_5['반납 스테이션 번호']])).count()
df_station_day_return_count = station_day_return_count[['반납 시간']]
df_station_day_return_count.columns = ['스테이션 이용 횟수']
df_station_day_return_count_1 = df_station_day_return_count.reset_index()
df_station_day_return_count_1

             대여 시간 반납 스테이션 번호  스테이션 이용 횟수
0       2017-01-01          0         144
1       2017-01-01        101          11
2       2017-01-01        103           1
3       2017-01-01        104           3
4       2017-01-01        105           1
...            ...        ...         ...
157231  2019-12-31        346           3
157232  2019-12-31        347           1
157233  2019-12-31        349           1
157234  2019-12-31        350           2
157235  2019-12-31        351           2

[157236 rows x 3 columns]

In [ ]:
# pivot 데이터를 활용해서 최소,최대,평균 반납 스테이션과 이용 횟수 구하기
df_station_day_return_count_pivot = df_station_day_return_count_1.pivot('반납 스테이션 번호','대여 시간','스테이션 이용 횟수')
df_station_day_return_count_pivot_1 = df_station_day_return_count_pivot.fillna(0) # 0값으로 채워준다.
df_station_day_return_count_pivot_1

대여 시간       2017-01-01  2017-01-02  ...  2019-12-30  2019-12-31
반납 스테이션 번호                          ...
0                144.0       185.0  ...       205.0       128.0
101               11.0         6.0  ...         5.0         2.0
103                1.0         2.0  ...         0.0         0.0
104                3.0         4.0  ...         4.0         7.0
105                1.0         0.0  ...         1.0         0.0
...                ...         ...  ...         ...         ...
350                4.0         1.0  ...         4.0         2.0
351                0.0         0.0  ...         4.0         2.0
992                0.0         0.0  ...         0.0         0.0
998                0.0         0.0  ...         0.0         0.0
999                0.0         0.0  ...         0.0         0.0

[158 rows x 1095 columns]

In [ ]:
# 스테이션 별 반납스테이션 최대 이용 횟수 및 최대 이용 날짜
def top(df):
    return df.sort_values(by="스테이션 이용 횟수", ascending=False)[:1]

df_station_day_return_maxcount_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(top)
df_station_day_return_maxcount_2 = df_station_day_return_maxcount_1.drop(['반납 스테이션 번호'],axis=1)
df_station_day_return_maxcount_3 = df_station_day_return_maxcount_2.reset_index()
df_station_day_return_maxcount_end = df_station_day_return_maxcount_3.drop(['level_1'],axis=1)
df_station_day_return_maxcount_end.columns = ['반납 스테이션 번호','최대 이용일', '최대 스테이션 이용 횟수']
df_station_day_return_maxcount_end

    반납 스테이션 번호      최대 이용일  최대 스테이션 이용 횟수
0            0  2019-10-13           1600
1          101  2017-06-02             27
2          103  2017-09-16             25
3          104  2017-06-13             30
4          105  2017-09-21             12
..         ...         ...            ...
153        350  2018-07-11             22
154        351  2019-10-29             31
155        992  2017-09-26              9
156        998  2019-11-30             15
157        999  2017-04-10              1

[158 rows x 3 columns]

In [ ]:
# 스테이션 별 반납스테이션 최소 이용 횟수 및 최소 이용 날짜
def bottom(df):
    return df.sort_values(by="스테이션 이용 횟수", ascending=True)[:1]

df_station_day_return_mincount_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(bottom)
df_station_day_return_mincount_2 = df_station_day_return_mincount_1.drop(['반납 스테이션 번호'], axis=1)
df_station_day_return_mincount_3 = df_station_day_return_mincount_2.reset_index()
df_station_day_return_mincount_end = df_station_day_return_mincount_3.drop(['level_1'], axis=1)
df_station_day_return_mincount_end.columns = ['반납 스테이션 번호','최소 이용일', '최소 스테이션 이용 횟수']
df_station_day_return_mincount_end

    반납 스테이션 번호      최소 이용일  최소 스테이션 이용 횟수
0            0  2017-01-29             27
1          101  2019-12-07              1
2          103  2017-01-01              1
3          104  2019-03-04              1
4          105  2017-01-01              1
..         ...         ...            ...
153        350  2019-09-14              1
154        351  2019-12-03              1
155        992  2017-01-04              1
156        998  2019-12-19              1
157        999  2017-04-10              1

[158 rows x 3 columns]

In [ ]:
# 스테이션 별 median()중간수
def median(df):
    return df.median()

df_station_day_return_mediancount_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(median)
df_station_day_return_mediancount_2 = df_station_day_return_mediancount_1.drop(['반납 스테이션 번호'], axis=1)
df_station_day_return_mediancount_end = df_station_day_return_mediancount_2.reset_index()
df_station_day_return_mediancount_end.columns = ['반납 스테이션 번호','스테이션 이용 횟수(quartile50)']
df_station_day_return_mediancount_end

    반납 스테이션 번호  스테이션 이용 횟수(quartile50)
0            0                   350.0
1          101                     8.0
2          103                     5.0
3          104                     8.0
4          105                     2.0
..         ...                     ...
153        350                     3.0
154        351                     5.0
155        992                     1.0
156        998                     2.5
157        999                     1.0

[158 rows x 2 columns]

In [ ]:
# 스테이션 별 4분위-25
def quantile_25(df):
    return df.quantile(.25)

df_station_day_return_qua25count_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(quantile_25)
df_station_day_return_qua25count_end = df_station_day_return_qua25count_1.reset_index()
df_station_day_return_qua25count_end.columns = ['반납 스테이션 번호','스테이션 이용 횟수(quartile25)']
df_station_day_return_qua25count_end

    반납 스테이션 번호  스테이션 이용 횟수(quartile25)
0            0                  202.00
1          101                    4.00
2          103                    2.00
3          104                    4.00
4          105                    1.00
..         ...                     ...
153        350                    2.00
154        351                    3.00
155        992                    1.00
156        998                    1.75
157        999                    1.00

[158 rows x 2 columns]

In [ ]:
# 스테이션 별 4분위-75
def quantile_75(df):
    return df.quantile(.75)

df_station_day_return_qua75count_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(quantile_75)
df_station_day_return_qua75count_end = df_station_day_return_qua75count_1.reset_index()
df_station_day_return_qua75count_end.columns = ['반납 스테이션 번호','스테이션 이용 횟수(quartile75)']
df_station_day_return_qua75count_end

    반납 스테이션 번호  스테이션 이용 횟수(quartile75)
0            0                   480.0
1          101                    13.0
2          103                     8.0
3          104                    13.0
4          105                     4.0
..         ...                     ...
153        350                     5.0
154        351                     7.0
155        992                     2.0
156        998                     6.0
157        999                     1.0

[158 rows x 2 columns]

In [ ]:
# 스테이션 별 평균
def mean(df):
    return df.mean().round(2)
 
df_station_day_return_meancount_1 = df_station_day_return_count_1.groupby(df_station_day_return_count_1['반납 스테이션 번호']).apply(mean) 
df_station_day_return_meancount_2 = df_station_day_return_meancount_1[['스테이션 이용 횟수']]
df_station_day_return_meancount_end = df_station_day_return_meancount_2.reset_index()
df_station_day_return_meancount_end.columns = ['반납 스테이션 번호','스테이션 평균 이용 횟수']
df_station_day_return_meancount_end

    반납 스테이션 번호  스테이션 평균 이용 횟수
0            0         363.68
1          101           8.72
2          103           5.32
3          104           8.75
4          105           3.02
..         ...            ...
153        350           3.88
154        351           5.97
155        992           1.68
156        998           5.25
157        999           1.00

[158 rows x 2 columns]

In [ ]:
# 스테이션 기준으로 각 1년간 반납 스테이션 이용 횟수
station_return_2017totalcount =  (df_OH_6.groupby([df_OH_6['대여 시간'],df_OH_6['반납 스테이션 번호']])).count()
station_return_2017totalcount_1 = station_return_2017totalcount[['대여 스테이션 번호']]
station_return_2017totalcount_1

                  대여 스테이션 번호
대여 시간 반납 스테이션 번호
2017  0               107810
      101               3648
      103               2155
      104               3703
      105                944
...                      ...
2019  350                986
      351                406
      992                291
      998                 21
      999                  3

[462 rows x 1 columns]

In [ ]:
# 스테이션 기준으로 각 1년간 반납 스테이션 이용 횟수(2017)
station_return_2017totalcount_2 = station_return_2017totalcount_1[:151]
station_return_2017totalcount_3 = station_return_2017totalcount_2.reset_index()
station_return_2017totalcount_end = station_return_2017totalcount_3[['반납 스테이션 번호','대여 스테이션 번호']]
station_return_2017totalcount_end.columns = ['반납 스테이션 번호','2017년 총 스테이션 이용 횟수']
station_return_2017totalcount_end

    반납 스테이션 번호  2017년 총 스테이션 이용 횟수
0            0              107810
1          101                3648
2          103                2155
3          104                3703
4          105                 944
..         ...                 ...
146        348                1052
147        349                2737
148        350                1628
149        992                 233
150        999                   3

[151 rows x 2 columns]

In [ ]:
station_return_2018totalcount_2 = station_return_2017totalcount_1[151:304]
station_return_2018totalcount_3 = station_return_2018totalcount_2.reset_index()
station_return_2018totalcount_end = station_return_2017totalcount_3[['반납 스테이션 번호','대여 스테이션 번호']]
station_return_2018totalcount_end.columns = ['반납 스테이션 번호','2018년 총 스테이션 이용 횟수']
station_return_2018totalcount_end

    반납 스테이션 번호  2018년 총 스테이션 이용 횟수
0            0              107810
1          101                3648
2          103                2155
3          104                3703
4          105                 944
..         ...                 ...
146        348                1052
147        349                2737
148        350                1628
149        992                 233
150        999                   3

[151 rows x 2 columns]

In [ ]:
station_return_2019totalcount_2 = station_return_2017totalcount_1[304:]
station_return_2019totalcount_3 = station_return_2019totalcount_2.reset_index()
station_return_2019totalcount_end = station_return_2019totalcount_3[['반납 스테이션 번호','대여 스테이션 번호']]
station_return_2019totalcount_end.columns = ['반납 스테이션 번호','2019년 총 스테이션 이용 횟수']
station_return_2019totalcount_end

    반납 스테이션 번호  2019년 총 스테이션 이용 횟수
0            0              169615
1          101                2772
2          103                1425
3          104                2751
4          105                 983
..         ...                 ...
153        350                 986
154        351                 406
155        992                 291
156        998                  21
157        999                   3

[158 rows x 2 columns]

### 스테이션 별  평균 이용 시간 / 평균 추정 이동 거리

In [ ]:
## 평균 이용 시간 구하기
df_OH_return_mean_time = df_OH_5[['대여 시간','반납 스테이션 번호','이용 시간(s)']] # 필요한 컬럼만 가져 온다.
df_OH_return_mean_time_1 = (df_OH_return_mean_time.groupby([df_OH_return_mean_time['대여 시간'],df_OH_return_mean_time['반납 스테이션 번호']])).mean().round(2)
df_OH_return_mean_time_2 = df_OH_return_mean_time_1.reset_index() # index기준을 변경해준다
df_OH_return_mean_time_2

             대여 시간 반납 스테이션 번호  이용 시간(s)
0       2017-01-01          0   4179.10
1       2017-01-01        101   1489.55
2       2017-01-01        103   1896.00
3       2017-01-01        104   2526.00
4       2017-01-01        105    611.00
...            ...        ...       ...
157231  2019-12-31        346    969.67
157232  2019-12-31        347    455.00
157233  2019-12-31        349    610.00
157234  2019-12-31        350    831.00
157235  2019-12-31        351    570.50

[157236 rows x 3 columns]

In [ ]:
def mean(df):
    return df.mean().round(0)

df_OH_return_mean_time_3 = df_OH_return_mean_time_2.groupby(df_OH_return_mean_time_2['반납 스테이션 번호']).apply(mean)
df_OH_return_mean_time_3

               반납 스테이션 번호  이용 시간(s)
반납 스테이션 번호
0            0.000000e+00    3153.0
101                   inf    1471.0
103                   inf    2031.0
104                   inf    1469.0
105                   inf    1395.0
...                   ...       ...
350                   inf    1441.0
351         5.166932e+201    1280.0
992                   inf     874.0
998          2.497497e+11     399.0
999          1.000000e+29    8635.0

[158 rows x 2 columns]

In [ ]:
df_OH_return_mean_time_4 = df_OH_return_mean_time_3[['이용 시간(s)']]
df_OH_return_mean_time_5 = df_OH_return_mean_time_4.reset_index()
df_OH_return_mean_time_5.columns = ['반납 스테이션 번호','평균 이용 시간(s)']
df_OH_return_mean_time_end = df_OH_return_mean_time_5.assign(TEST=lambda x: ((x['평균 이용 시간(s)']/60).round(1)))
df_OH_return_mean_time_end.columns =['반납 스테이션 번호','평균 이용 시간(s)','평균 이용 시간(m)']
df_OH_return_mean_time_end

    반납 스테이션 번호  평균 이용 시간(s)  평균 이용 시간(m)
0            0       3153.0         52.6
1          101       1471.0         24.5
2          103       2031.0         33.8
3          104       1469.0         24.5
4          105       1395.0         23.2
..         ...          ...          ...
153        350       1441.0         24.0
154        351       1280.0         21.3
155        992        874.0         14.6
156        998        399.0          6.6
157        999       8635.0        143.9

[158 rows x 3 columns]

In [ ]:
df_OH_return_est_dis = df_OH_5[['대여 시간','반납 스테이션 번호','추정 이동 거리']] # 필요한 컬럼만 뽑아준다.
df_OH_return_est_dis_1 = df_OH_return_est_dis.dropna(axis=0) # 추정 이동 거리 가 있는 평균을 알고 싶기에 처음 NaN 값을 제거해준다.
df_OH_return_est_dis_2 = df_OH_return_est_dis_1[df_OH_return_est_dis_1['추정 이동 거리']!=0] # 0으로 된 추정이동거리 값도 제거해준다.
df_OH_return_est_dis_2

              대여 시간 반납 스테이션 번호  추정 이동 거리
1        2017-01-01        231   31039.0
3        2017-01-01        133   15490.0
6        2017-01-01        213    8948.0
8        2017-01-01        113   17482.0
11       2017-01-01        231   15170.0
...             ...        ...       ...
3142652  2019-12-31        303    3041.0
3142657  2019-12-31        319   14111.0
3142668  2019-12-31        226   38894.0
3142673  2019-12-31        218   37720.0
3142687  2019-12-31        222   33169.0

[660148 rows x 3 columns]

In [ ]:
# 각각의 대여시간별 스테이션 번호의 평균 추정이동거리 값을 구해준다
df_OH_return_est_dis_mean = (df_OH_return_est_dis_2.groupby([df_OH_return_est_dis_2['대여 시간'],df_OH_return_est_dis_2['반납 스테이션 번호']])).mean()
df_OH_return_est_dis_mean_1 = df_OH_return_est_dis_mean.reset_index()
df_OH_return_est_dis_mean_1

             대여 시간 반납 스테이션 번호  추정 이동 거리
0       2017-01-01        101  24549.25
1       2017-01-01        103  57959.00
2       2017-01-01        104  14066.00
3       2017-01-01        106  28749.00
4       2017-01-01        110  34432.00
...            ...        ...       ...
103083  2019-12-31        331   8896.00
103084  2019-12-31        333  12599.00
103085  2019-12-31        339  44562.00
103086  2019-12-31        343  26627.25
103087  2019-12-31        345  11874.00

[103088 rows x 3 columns]

In [ ]:
# 스테이션을 기준으로 반납 스테이션의 3년간 추정 이동 거리의 평균을 구해 준다.
def mean(df):
    return df.mean().round(2)

df_OH_return_est_dis_mean_2 = df_OH_return_est_dis_mean_1.groupby(df_OH_return_est_dis_mean_1['반납 스테이션 번호']).apply(mean)
df_OH_return_est_dis_mean_2

            반납 스테이션 번호  추정 이동 거리
반납 스테이션 번호
0                  0.0  28830.37
101                inf  24583.01
103                inf  24206.09
104                inf  19578.52
105                inf  21646.73
...                ...       ...
339                inf  28877.62
340                inf  14387.93
341                inf  24448.94
343                inf  22702.65
345                inf  29344.66

[119 rows x 2 columns]

In [ ]:
df_OH_return_est_dis_mean_2.columns = ['1','추정 이동 거리']
df_OH_return_est_dis_mean_3 = df_OH_return_est_dis_mean_2.reset_index()
df_OH_return_est_dis_mean_end = df_OH_return_est_dis_mean_3[['반납 스테이션 번호','추정 이동 거리']]
df_OH_return_est_dis_mean_end.columns = ['반납 스테이션 번호','추정 이동 거리 평균']
df_OH_return_est_dis_mean_end

    반납 스테이션 번호  추정 이동 거리 평균
0            0     28830.37
1          101     24583.01
2          103     24206.09
3          104     19578.52
4          105     21646.73
..         ...          ...
114        339     28877.62
115        340     14387.93
116        341     24448.94
117        343     22702.65
118        345     29344.66

[119 rows x 2 columns]

In [ ]:
df_return_rate_1 = pd.read_csv('3년간 스테이션 별 자전거 반납 스테이션 이용 현황.csv',index_col=0)

In [ ]:
df_return_rate_2 = pd.merge(df_return_rate_1,df_bike_return,on='반납 스테이션 번호',how='left')
df_return_rate_2

     반납 스테이션 번호  전체 인원 반납 스테이션 이용 횟수  ...      반납 위도       반납 경도
0             0               398234  ...        NaN         NaN
1           101                 9207  ...  37.654775  126.834584
2           103                 5121  ...  37.660442  126.840377
3           104                 9330  ...  37.698523  126.766042
4           105                 2696  ...  37.655244  126.839261
..          ...                  ...  ...        ...         ...
153         350                 3662  ...  37.697867  126.753089
154         351                  406  ...  37.702259  126.767231
155         992                  795  ...  37.637529  126.833760
156         998                   21  ...        NaN         NaN
157         999                   10  ...        NaN         NaN

[158 rows x 8 columns]

In [ ]:
df_return_rate_3 = df_return_rate_2.assign(TEST=lambda x: ((x['회원 반납 스테이션 이용 횟수']/x['전체 인원 반납 스테이션 이용 횟수']).round(2)))
df_return_rate_4 = df_return_rate_3.assign(TEST1=lambda x: (1-x['TEST']))
df_return_rate_end = df_return_rate_4[['반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','전체 인원 반납 스테이션 이용 횟수','TEST','TEST1','반납 위도','반납 경도']]
df_return_rate_end.columns = ['반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','전체 인원 반납 스테이션 이용 횟수','회원 비율','비회원 비율','위도','경도']
df_return_rate_end['반납 스테이션 번호']=df_return_rate_end[['반납 스테이션 번호']].astype('str') #merge 하기위해 data타입 변경
df_return_rate_end

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

    반납 스테이션 번호       반납 STATION_NAME  반납 거치대 수량  ...  비회원 비율         위도          경도
0            0                   NaN        NaN  ...    0.22        NaN         NaN
1          101          어울림마을 701동 앞       20.0  ...    0.38  37.654775  126.834584
2          103          대림e-편한세상106동       20.0  ...    0.53  37.660442  126.840377
3          104               탄현마을8단지       25.0  ...    0.27  37.698523  126.766042
4          105             KT 덕양지사 앞       20.0  ...    0.35  37.655244  126.839261
..         ...                   ...        ...  ...     ...        ...         ...
153        350  ★하이파크5단지 502동앞 버스정류장       20.0  ...    0.24  37.697867  126.753089
154        351          ◆일산에듀포레 푸르지오       40.0  ...    0.22  37.702259  126.767231
155        992                ★피프틴센터        4.0  ...    0.05  37.637529  126.833760
156        998                   NaN        NaN  ...    0.00        NaN         NaN
157        999                   NaN        NaN  ...    0.00        NaN         NaN

[158 rows x 8 columns]

## 데이터 프레임 merge

In [ ]:
df = pd.merge(df_return_rate_end,df_station_day_return_maxcount_end, on='반납 스테이션 번호', how='left') # 최대 스테이션 이요 횟수 및 날자 merge
df_1 = pd.merge(df, df_station_day_return_mincount_end, on='반납 스테이션 번호', how='left')  # # 최소 스테이션 이용 횟수 및 날짜
df_2 = pd.merge(df_1,df_station_day_return_qua25count_end, on='반납 스테이션 번호', how='left') # 25 스테이션 이용 횟수 및 날짜
df_3 = pd.merge(df_2,df_station_day_return_mediancount_end, on='반납 스테이션 번호', how='left') # 50 스테이션 이용 횟수 및 날짜
df_4 = pd.merge(df_3, df_station_day_return_qua75count_end , on='반납 스테이션 번호', how='left') # 75 스테이션 이용 횟수 및 날짜
df_5 = pd.merge(df_4, df_station_day_return_meancount_end, on='반납 스테이션 번호', how='left') # 평균 스테이션 이용 횟수 및 날짜
df_6 = pd.merge(df_5, station_return_2017totalcount_end, on='반납 스테이션 번호', how='left') # 2017
df_7 = pd.merge(df_6, station_return_2018totalcount_end, on='반납 스테이션 번호', how='left') # 2018
df_8 = pd.merge(df_7, station_return_2019totalcount_end, on='반납 스테이션 번호', how='left')  # 2019
df_9 = pd.merge(df_8, df_OH_return_est_dis_mean_end , on='반납 스테이션 번호', how='left')  # 추정 이동거리 평균
df_10 = pd.merge(df_9, df_OH_return_mean_time_end, on='반납 스테이션 번호', how='left') # 평균 이용 시간
df_Daily_return_station_usage_status = df_10[['반납 스테이션 번호','반납 STATION_NAME','반납 거치대 수량','전체 인원 반납 스테이션 이용 횟수','2017년 총 스테이션 이용 횟수','2018년 총 스테이션 이용 횟수','2019년 총 스테이션 이용 횟수','추정 이동 거리 평균','평균 이용 시간(s)','평균 이용 시간(m)','회원 비율','비회원 비율','스테이션 평균 이용 횟수','최대 이용일','최소 이용일','최대 스테이션 이용 횟수','스테이션 이용 횟수(quartile75)','스테이션 이용 횟수(quartile50)','스테이션 이용 횟수(quartile25)','최소 스테이션 이용 횟수','위도','경도']]
df_Daily_return_station_usage_status

    반납 스테이션 번호       반납 STATION_NAME  ...         위도          경도
0            0                   NaN  ...        NaN         NaN
1          101          어울림마을 701동 앞  ...  37.654775  126.834584
2          103          대림e-편한세상106동  ...  37.660442  126.840377
3          104               탄현마을8단지  ...  37.698523  126.766042
4          105             KT 덕양지사 앞  ...  37.655244  126.839261
..         ...                   ...  ...        ...         ...
153        350  ★하이파크5단지 502동앞 버스정류장  ...  37.697867  126.753089
154        351          ◆일산에듀포레 푸르지오  ...  37.702259  126.767231
155        992                ★피프틴센터  ...  37.637529  126.833760
156        998                   NaN  ...        NaN         NaN
157        999                   NaN  ...        NaN         NaN

[158 rows x 22 columns]

In [ ]:
df_Daily_return_station_usage_status['스테이션 이용 횟수(quartile25)'].describe()

count    158.000000
mean       9.550633
std       17.221320
min        1.000000
25%        3.000000
50%        6.000000
75%       12.000000
max      202.000000
Name: 스테이션 이용 횟수(quartile25), dtype: float64